### PR TITLE
Normalize anonymous namespace between platforms (#145)

### LINKED ISSUE #145: normalize "anonymous namespace" signatures
From https://bugzilla.mozilla.org/show_bug.cgi?id=1672847 , dmajor wrote:

> For signatures with anonymous namespaces, Windows crash reports say
> 
> ```
> `anonymous namespace'::foo
> ```
> 
> With a backtick and a single quote. Mac and Linux use parens:
> 
> ```
> (anonymous namespace)::foo
> ```
> 
> This can lead to a misleading picture of crash distribution if you're only searching for one and not the other. Can/should we pick one style and use it everywhere?

@calixteman said the fix should go here:

https://github.com/mozilla/dump_syms/blob/1e64e56720131bcf0ab01f201ed89a337c73069d/src/common.rs#L80

### PR DESCRIPTION
**Pull request by willkg**
On Windows, the symbol is:

```
`anonymous namespace'
```

and on Mac and Linux, we get:

```
(anonymous namespace)
```

This normalizes Windows to be like Mac and Linux.

Fixes #145.

### CODE REVIEW

File: src/common.rs [hunk 1]
```diff
@@ -83,6 +83,9 @@ pub(crate) fn fix_symbol_name<'a>(name: &'a Name<'a>) -> Name<'a> {
     }
     let fixed = LLVM_NNN.replace(name.as_str(), "");
 
+    // Normalize anonymous namespace symbol between platforms
```
Comment (willkg) [inline src/common.rs:86]: I noticed this file has no comments. I'm game for removing this one if it's unhelpful.

Comment (gabrielesvelto) [reply src/common.rs:86]: Turn it into a small function with a descriptive name instead, like `normalize_anonymous_namespace()` that's the best way to document code w/o risking for the comments to go out-of-date. I'm always super positive about splitting out one- or two-line functions if it means describing what's happening; it makes reading the code a smoother experience.

**Review by gabrielesvelto — CHANGES_REQUESTED** [review]

**Comment by willkg** [comment]
@gabrielesvelto I adjusted it. Does that work better?

**Review by gabrielesvelto — APPROVED** [review]
Thanks!
